---
name: 'release'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: 'New Release'
    runs-on: 'ubuntu-16.04'

    steps:
      - name: 'git checkout source'
        uses: 'actions/checkout@v1'
        with:
          lfs: true

      - name: 'Set up JDK 11'
        uses: 'actions/setup-java@v1'
        with:
          java-version: '11.x'

      - name: 'Download FIT SDK'
        env:
          FIT_SDK_VERSION: '20.96.00'
        run: |
          curl --progress-bar -o /tmp/FitSDKRelease_${FIT_SDK_VERSION}.zip https://www.thisisant.com/assets/resources/FIT/FitSDKRelease_${FIT_SDK_VERSION}.zip
          unzip -j /tmp/FitSDKRelease_${FIT_SDK_VERSION}.zip "java/fit.jar" -d ./

      - name: 'Generate release jar file'
        env:
          TZ: 'America/Toronto'
        run: 'mvn --no-transfer-progress clean verify package'

      - name: 'Rename the release jar file'
        run: 'cp target/activity-manager-*-jar-with-dependencies.jar target/activity-manager.jar'

      - name: 'Create GitHub release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: 'softprops/action-gh-release@v1'
        with:
          files: 'target/activity-manager.jar'
